name: Build and publish Docker container

on:
  push:
    branches:
      - main
      - ghcr

jobs:
  build-and-publish:
    name: Build and publish Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build --tag ghcr.io/jsha/unboundtest:latest .

      - name: Push
        run: docker push ghcr.io/jsha/unboundtest:latest
